spring:
  application:
    name: backend

########################################
###  spring doc ??
########################################
springdoc:
  apiVersion: '1.0.0'
  title: Wanted Pre-onboarding Challenge Backend
  description: API Document
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-produces-media-type: application/json
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    displayRequestDuration: true
    defaultModelsExpandDepth: 3
    defaultModelExpandDepth: 3